#!/usr/bin/env python3
"""Build the airtime bench sample from the AMI Meeting Corpus manual annotations, and print
the Python reference canon that the browser engine (assets/airtime-live.js) must reproduce.

Source: AMI Meeting Corpus, manual annotations release 1.7 (ami_public_manual_1.6.2.zip),
https://groups.inf.ed.ac.uk/ami/download/ - licensed CC BY 4.0 (LICENCE.txt in the zip).
Citation: Carletta, J. et al. (2005) The AMI Meeting Corpus: A Pre-announcement. MLMI 2005,
LNCS 3869, Springer.

What is shipped (derived, modified): for a seeded sample of scenario meetings, each speaker
segment's speaker index, start time and duration, as integer centiseconds. No audio, no words,
no participant ids. Roles come from corpusResources/meetings.xml.

Usage:
  python3 build-ami-airtime.py <path-to-unzipped-ami-manual-annotations> <repo>   # build + canon
  python3 build-ami-airtime.py --canon <repo>                                     # canon only
  python3 build-ami-airtime.py --json <repo>                                      # canon as JSON
  node materials/airtime-node.js <repo>                                           # same, from the browser engine
"""
from __future__ import annotations

import json
import random
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

SEED = 20261006
N_GROUPS = 10
ROLES = ["PM", "ME", "UI", "ID"]  # project manager, marketing expert, user interface, industrial designer
AGENTS = ["A", "B", "C", "D"]
BAD_TIMING = {"TS3009"}  # README: timings incomplete for TS3009c channel 3
NITE = "{http://nite.sourceforge.net/}"


# ---------------------------------------------------------------- build
def build(ami: Path, repo: Path) -> None:
    root = ET.parse(ami / "corpusResources" / "meetings.xml").getroot()
    meetings = {}
    for m in root.iter("meeting"):
        if m.get("type") != "scenario":
            continue
        roles = {}
        for s in m.iter("speaker"):
            roles[s.get("nxt_agent")] = s.get("role")
        meetings[m.get("observation")] = roles
    groups: dict[str, list[str]] = {}
    for obs in meetings:
        groups.setdefault(obs[:6], []).append(obs)
    eligible = []
    for g, obs in sorted(groups.items()):
        if g in BAD_TIMING or len(obs) != 4:
            continue
        ok = all(sorted(meetings[o]) == AGENTS and sorted(meetings[o].values()) == sorted(ROLES)
                 and all((ami / "segments" / f"{o}.{a}.segments.xml").exists() for a in AGENTS)
                 for o in obs)
        if ok:
            eligible.append(g)
    picked = sorted(random.Random(SEED).sample(eligible, N_GROUPS))
    out = []
    for g in picked:
        for obs in sorted(groups[g]):
            role_of_agent = [ROLES.index(meetings[obs][a]) for a in AGENTS]
            segs = []
            for ai, a in enumerate(AGENTS):
                t = ET.parse(ami / "segments" / f"{obs}.{a}.segments.xml").getroot()
                for seg in t.iter("segment"):
                    st, en = seg.get("transcriber_start"), seg.get("transcriber_end")
                    st, en = round(float(st) * 100), round(float(en) * 100)
                    if en > st:
                        segs.append((st, en - st, ai))
            segs.sort()
            # delta-encode start times; durations raw
            starts, durs, spk = [], [], []
            prev = 0
            for st, du, ai in segs:
                starts.append(st - prev)
                prev = st
                durs.append(du)
                spk.append(ai)
            out.append({"id": obs, "role": role_of_agent, "ds": starts, "du": durs, "sp": spk})
    data = {
        "source": "AMI Meeting Corpus manual annotations 1.7, CC BY 4.0, segment timings only",
        "eligibleGroups": len(eligible),
        "seed": SEED,
        "roles": ROLES,
        "meetings": out,
    }
    js = "/* Derived from the AMI Meeting Corpus (CC BY 4.0, groups.inf.ed.ac.uk/ami). Modified: " \
         "segment start/duration/speaker only, centiseconds. Generated by materials/build-ami-airtime.py */\n" \
         "window.AMI_SAMPLE = " + json.dumps(data, separators=(",", ":")) + ";\n"
    (repo / "assets" / "ami-sample.js").write_text(js)
    print(f"eligible groups {len(eligible)}, picked {picked}, meetings {len(out)}, "
          f"segments {sum(len(m['sp']) for m in out)}, bytes {len(js)}")


# ---------------------------------------------------------------- engine (mirror of airtime-live.js)
def load(repo: Path) -> dict:
    txt = (repo / "assets" / "ami-sample.js").read_text()
    data = json.loads(txt[txt.index("{"): txt.rindex("}") + 1])
    for m in data["meetings"]:
        segs, t = [], 0
        for d, du, sp in zip(m["ds"], m["du"], m["sp"]):
            t += d
            segs.append([t, t + du, sp])
        m["segs"] = segs
    return data


def mulberry32(a: int):
    def nxt() -> float:
        nonlocal a
        a = (a + 0x6D2B79F5) & 0xFFFFFFFF
        t = a
        t = ((t ^ (t >> 15)) * (t | 1)) & 0xFFFFFFFF
        t = (t ^ ((t + (((t ^ (t >> 7)) * (t | 61)) & 0xFFFFFFFF)) & 0xFFFFFFFF)) & 0xFFFFFFFF
        return ((t ^ (t >> 14)) & 0xFFFFFFFF) / 4294967296
    return nxt


def gini(xs: list[float]) -> float:
    n = len(xs)
    tot = 0.0
    for v in xs:
        tot += v
    if tot == 0:
        return 0.0
    s = 0.0
    for a in xs:
        for b in xs:
            s += abs(a - b)
    return s / (2 * n * tot)


def measure(segs: list[list[int]]) -> dict:
    """segs sorted by (start, end, spk). Returns per-speaker time (union, cs), turns, overlaps."""
    time = [0, 0, 0, 0]
    for k in range(4):
        cur_s = cur_e = -1
        for s, e, sp in segs:
            if sp != k:
                continue
            if s > cur_e:
                if cur_e > cur_s:
                    time[k] += cur_e - cur_s
                cur_s, cur_e = s, e
            elif e > cur_e:
                cur_e = e
        if cur_e > cur_s:
            time[k] += cur_e - cur_s
    turns = [0, 0, 0, 0]
    last = -1
    for s, e, sp in segs:
        if sp != last:
            turns[sp] += 1
            last = sp
    ov = [[0] * 4 for _ in range(4)]  # ov[y][x]: y started speaking while x was mid-segment
    fl = [[0] * 4 for _ in range(4)]  # ... and x stopped before y did (floor taken)
    active: list[list[int]] = []
    for s, e, sp in segs:
        active = [a for a in active if a[1] > s]
        for a in active:
            if a[2] != sp and a[0] < s:
                ov[sp][a[2]] += 1
                if a[1] < e:
                    fl[sp][a[2]] += 1
        active.append([s, e, sp])
    span = max(e for _, e, _ in segs) - segs[0][0]
    tot = time[0] + time[1] + time[2] + time[3]
    share = [t / tot for t in time]
    nturns = turns[0] + turns[1] + turns[2] + turns[3]
    return {"time": time, "share": share, "gini": gini(share), "top": max(share),
            "topIdx": share.index(max(share)), "turns": turns, "turnsPerMin": nturns / (span / 6000),
            "ov": ov, "fl": fl, "span": span}


def cap_shares(share: list[float], cap: float) -> list[float]:
    """Round-robin cap (declared simulation): nobody above `cap`; the excess is handed out in
    equal parts to everyone below the cap, repeated until nobody is over. Total stays 1."""
    s = share[:]
    for _ in range(12):
        excess = 0.0
        for i in range(4):
            if s[i] > cap:
                excess += s[i] - cap
                s[i] = cap
        if excess <= 1e-12:
            break
        under = [i for i in range(4) if s[i] < cap]
        if not under:
            break
        add = excess / len(under)
        for i in under:
            s[i] += add
    return s


def loudest_summarises(segs: list[list[int]], top: int, frac: float = 0.10) -> list[list[int]]:
    """Anti-lever model: every segment starting in the last `frac` of the meeting span is
    re-labelled to the baseline top speaker."""
    t0 = segs[0][0]
    t1 = max(e for _, e, _ in segs)
    cut = t1 - frac * (t1 - t0)
    out = [[s, e, top if s >= cut else sp] for s, e, sp in segs]
    out.sort()
    return out


def shuffle_labels(segs: list[list[int]], seed: int) -> list[list[int]]:
    """Break button: each segment gets a speaker drawn uniformly from the four (seeded)."""
    r = mulberry32(seed)
    out = [[s, e, int(r() * 4)] for s, e, _ in segs]
    out.sort()
    return out


def seed_for(mid: str) -> int:
    h = 2166136261
    for ch in mid:
        h ^= ord(ch)
        h = (h * 16777619) & 0xFFFFFFFF
    return h


def canon(repo: Path) -> dict:
    data = load(repo)
    ms = data["meetings"]
    res = {"meetings": len(ms), "segments": sum(len(m["segs"]) for m in ms)}
    per = []
    for m in ms:
        b = measure(m["segs"])
        role = m["role"]
        pm = role.index(0)
        c40 = cap_shares(b["share"], 0.40)
        c30 = cap_shares(b["share"], 0.30)
        ls = measure(loudest_summarises(m["segs"], b["topIdx"]))
        sh = measure(shuffle_labels(m["segs"], seed_for(m["id"])))
        per.append({"id": m["id"], "role": role, "pm": pm, "b": b, "g40": gini(c40), "t40": max(c40),
                    "g30": gini(c30), "t30": max(c30), "ls": ls, "sh": sh})
    n = len(per)
    mean = lambda xs: sum(xs) / len(xs)
    res["meanGini"] = mean([p["b"]["gini"] for p in per])
    res["meanTop"] = mean([p["b"]["top"] for p in per])
    res["minGini"] = min(p["b"]["gini"] for p in per)
    res["maxGini"] = max(p["b"]["gini"] for p in per)
    res["pmTopCount"] = sum(1 for p in per if p["b"]["topIdx"] == p["pm"])
    res["roleShare"] = [mean([p["b"]["share"][p["role"].index(r)] for p in per]) for r in range(4)]
    res["roleTurns"] = [mean([p["b"]["turns"][p["role"].index(r)] / sum(p["b"]["turns"]) for p in per])
                        for r in range(4)]
    res["meanTurnsPerMin"] = mean([p["b"]["turnsPerMin"] for p in per])
    res["meanGini40"] = mean([p["g40"] for p in per])
    res["meanGini30"] = mean([p["g30"] for p in per])
    res["pmTopCount30"] = 0
    for p in per:
        c = cap_shares(p["b"]["share"], 0.30)
        top = max(c)
        n_top = sum(1 for v in c if top - v < 1e-9)
        if n_top == 1 and c.index(top) == p["pm"]:
            res["pmTopCount30"] += 1
    res["roleShare30"] = [mean([cap_shares(p["b"]["share"], 0.30)[p["role"].index(r)] for p in per]) for r in range(4)]
    res["meanGiniLS"] = mean([p["ls"]["gini"] for p in per])
    res["meanTopLS"] = mean([p["ls"]["top"] for p in per])
    res["lsRaised"] = sum(1 for p in per if p["ls"]["gini"] > p["b"]["gini"])
    res["meanGiniSH"] = mean([p["sh"]["gini"] for p in per])
    res["pmTopCountSH"] = sum(1 for p in per if p["sh"]["topIdx"] == p["pm"])
    res["roleShareSH"] = [mean([p["sh"]["share"][p["role"].index(r)] for p in per]) for r in range(4)]
    # overlaps: who starts over whom, by role, summed over the sample
    ovr = [[0] * 4 for _ in range(4)]
    flr = [[0] * 4 for _ in range(4)]
    for p in per:
        for y in range(4):
            for x in range(4):
                ovr[p["role"][y]][p["role"][x]] += p["b"]["ov"][y][x]
                flr[p["role"][y]][p["role"][x]] += p["b"]["fl"][y][x]
    res["byPhase"] = []
    for ph in "abcd":
        sub = [p for p in per if p["id"][-1] == ph]
        res["byPhase"].append({"phase": ph, "n": len(sub), "meanGini": mean([p["b"]["gini"] for p in sub]),
                               "pmShare": mean([p["b"]["share"][p["pm"]] for p in sub]),
                               "pmTop": sum(1 for p in sub if p["b"]["topIdx"] == p["pm"])})
    res["ovByRole"] = ovr
    res["flByRole"] = flr
    res["perMeeting"] = [{"id": p["id"], "gini": p["b"]["gini"], "top": p["b"]["top"],
                          "topRole": ROLES[p["role"][p["b"]["topIdx"]]], "share": p["b"]["share"],
                          "turnsPerMin": p["b"]["turnsPerMin"], "g40": p["g40"], "g30": p["g30"],
                          "gLS": p["ls"]["gini"], "gSH": p["sh"]["gini"]} for p in per]
    return res


def fmt(res: dict) -> str:
    r = lambda v, d=4: round(v, d)
    lines = [f"meetings {res['meetings']} segments {res['segments']}",
             f"meanGini {r(res['meanGini'])} min {r(res['minGini'])} max {r(res['maxGini'])} meanTop {r(res['meanTop'])}",
             f"pmTop {res['pmTopCount']} roleShare {[r(x) for x in res['roleShare']]} roleTurns {[r(x) for x in res['roleTurns']]}",
             f"turnsPerMin {r(res['meanTurnsPerMin'])}",
             f"cap40 {r(res['meanGini40'])} cap30 {r(res['meanGini30'])}",
             f"loudest {r(res['meanGiniLS'])} top {r(res['meanTopLS'])} raised {res['lsRaised']}",
             f"shuffle {r(res['meanGiniSH'])} pmTop {res['pmTopCountSH']} roleShare {[r(x) for x in res['roleShareSH']]}",
             f"ovByRole {res['ovByRole']}", f"flByRole {res['flByRole']}"]
    for p in res["perMeeting"]:
        lines.append(f"{p['id']} g {r(p['gini'])} top {r(p['top'])} {p['topRole']} share {[r(x) for x in p['share']]} "
                     f"tpm {r(p['turnsPerMin'])} g40 {r(p['g40'])} g30 {r(p['g30'])} gLS {r(p['gLS'])} gSH {r(p['gSH'])}")
    return "\n".join(lines)


if __name__ == "__main__":
    if sys.argv[1] == "--json":
        res = canon(Path(sys.argv[2]))
        print(json.dumps(res))
    elif sys.argv[1] == "--canon":
        print(fmt(canon(Path(sys.argv[2]))))
    else:
        build(Path(sys.argv[1]), Path(sys.argv[2]))
        print(fmt(canon(Path(sys.argv[2]))))
